setwd("C:/Users/Jirawech/Documents/#4assignment1")
data<-read.csv("household_power_consumption.txt", sep= ";")
ydata<-subset(data, Date == "1/2/2007" | Date == "2/2/2007")
ydata<-transform(ydata, Date= strptime(ydata$Date, format ='%d/%m/%Y') )
ydata$Date.time<-strptime(paste(ydata$Date, ydata$Time, sep="/"), format ='%Y-%m-%d/%H:%M:%S') 
png(filename="plot4.png", width = 480 , height = 480)
x1<-ydata$Date.time
y1<-as.numeric(as.character(ydata$Global_active_power))
ysub1<-as.numeric(as.character(ydata$Sub_metering_1))
ysub2<-as.numeric(as.character(ydata$Sub_metering_2))
ysub3<-as.numeric(as.character(ydata$Sub_metering_3))
yVol<-as.numeric(as.character(ydata$Voltage))
yre<-as.numeric(as.character(ydata$Global_reactive_power))
par(mfrow=c(2,2), mar= c(1,4.1,4.1,2.1))
plot(x1,y1, ylab="Global Active Power (kilowatts)", pch=' ', type = 'o')
plot(x1,yVol, ylab="Volage",xlab= "datetime", pch=' ', type = 'o')
plot(x1,ysub1, ylab="Energy sub metering", pch=' ', type = 'o')
points(x1,ysub2,pch=' ', type = 'o', col = 'red')
points(x1,ysub3,pch=' ', type = 'o', col = 'blue')
legend("topright", pch = 1, col=c("black", "red", "blue"), legend=c("Sub metering_1", "Sub metering_2", "Sub metering_3"))
plot(x1,yre, ylab="Global_reative_power", xlab="datetime", pch=" ", type = 'o')
dev.off()